apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../argo/apps/minio-appset.yaml
  - ../../argo/apps/redpanda-appset.yaml
  - ../../argo/apps/flink-appset.yaml
  - ../../argo/apps/starrocks-appset.yaml
  - ../../argo/apps/iceberg-appset.yaml

commonLabels:
  environment: prod
  cluster: prod

