# Production environment overrides for Flink Helm chart
namespace: prod

jobmanager:
  replicas: 2
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi

taskmanager:
  replicas: 3
  taskSlots: 4
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 4Gi

parallelism:
  default: 12

