apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - virtualservices/argocd-vs.yaml
  - virtualservices/redpanda-console-vs.yaml
  - virtualservices/kiali-vs.yaml
  - virtualservices/grafana-vs.yaml
  - argocd-config/configmap.yaml

