apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redpanda-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: redpanda-system
  template:
    metadata:
      name: redpanda-operator-{{environment}}
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: multipass
      source:
        repoURL: https://charts.redpanda.com
        targetRevision: 25.1.4
        chart: redpanda-operator
        helm:
          releaseName: redpanda-operator
          values: |
            crds:
              enabled: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

