apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redpanda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: redpanda
            valuesFile: ../../kustomize/overlays/dev/redpanda/values-dev.yaml
          - environment: staging
            namespace: redpanda
            valuesFile: ../../kustomize/overlays/staging/redpanda/values-staging.yaml
          - environment: prod
            namespace: redpanda
            valuesFile: ../../kustomize/overlays/prod/redpanda/values-prod.yaml
  template:
    metadata:
      name: redpanda-{{environment}}
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: multipass
      source:
        repoURL: https://github.com/coolsaigit/multipass.git
        targetRevision: main
        path: gitops/helm/redpanda
        helm:
          valueFiles:
            - values.yaml
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

