apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - virtualservices/argocd-vs.yaml
  - virtualservices/redpanda-console-vs.yaml
  - virtualservices/kiali-vs.yaml
  - virtualservices/grafana-vs.yaml
  - virtualservices/minio-vs.yaml
  - virtualservices/flink-vs.yaml
  - virtualservices/starrocks-vs.yaml
  - virtualservices/trino-vs.yaml
  - virtualservices/prometheus-vs.yaml
  - argocd-config/configmap.yaml

