namespace: redpanda

redpanda:
  replicas: 1
  image:
    repository: docker.redpanda.com/redpandadata/redpanda
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 20Gi

console:
  enabled: true
  image:
    repository: docker.redpanda.com/redpandadata/console
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

