{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda-console
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
        imagePullPolicy: {{ .Values.console.image.pullPolicy }}
        env:
        - name: KAFKA_BROKERS
          value: "redpanda.{{ .Values.namespace }}.svc.cluster.local:9092"
        - name: KAFKA_SCHEMAREGISTRY_ENABLED
          value: "true"
        - name: KAFKA_SCHEMAREGISTRY_URLS
          value: "http://redpanda.{{ .Values.namespace }}.svc.cluster.local:8081"
        - name: KAFKA_PRODUCER_ENABLED
          value: "true"
        - name: KAFKA_CONSUMER_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
          name: http
        resources:
          {{- toYaml .Values.console.resources | nindent 10 }}
{{- end }}

