apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: redpanda
spec:
  clusterSpec:
    image:
      tag: {{ .Values.image.tag | default "v25.2.11" }}
    statefulset:
      replicas: {{ .Values.statefulset.replicas | default 1 }}
      {{- if .Values.statefulset.podTemplate }}
      podTemplate:
        {{- toYaml .Values.statefulset.podTemplate | nindent 8 }}
      {{- end }}
    resources:
      {{- if .Values.resources }}
      {{- toYaml .Values.resources | nindent 6 }}
      {{- end }}
    storage:
      {{- if .Values.storage }}
      {{- toYaml .Values.storage | nindent 6 }}
      {{- end }}
    config:
      {{- if .Values.config }}
      {{- toYaml .Values.config | nindent 6 }}
      {{- end }}
    {{- if .Values.statefulset.extraVolumes }}
    extraVolumes: |-
      {{- .Values.statefulset.extraVolumes | nindent 6 }}
    {{- end }}
    {{- if .Values.statefulset.extraVolumeMounts }}
    extraVolumeMounts: |-
      {{- .Values.statefulset.extraVolumeMounts | nindent 6 }}
    {{- end }}
    {{- if .Values.statefulset.additionalRedpandaCmdFlags }}
    additionalRedpandaCmdFlags:
      {{- toYaml .Values.statefulset.additionalRedpandaCmdFlags | nindent 6 }}
    {{- end }}
  {{- if .Values.console }}
  console:
    {{- toYaml .Values.console | nindent 4 }}
  {{- end }}

