apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.namespace }}
  labels:
    app: redpanda
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka-internal
  - port: 19092
    targetPort: 19092
    name: kafka-external
  - port: 8081
    targetPort: 8081
    name: schema-registry-internal
  - port: 18081
    targetPort: 18081
    name: schema-registry-external
  - port: 8082
    targetPort: 8082
    name: pandaproxy-internal
  - port: 18082
    targetPort: 18082
    name: pandaproxy-external
  - port: 9644
    targetPort: 9644
    name: admin
  - port: 33145
    targetPort: 33145
    name: rpc
  selector:
    app: redpanda

