apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
  namespace: {{ .Values.namespace }}
data:
  redpanda.yaml.template: |
    redpanda:
      data_directory: /var/lib/redpanda/data
      {{- if gt (int .Values.redpanda.replicas) 1 }}
      seed_servers:
      {{- range $i := until (int .Values.redpanda.replicas) }}
        - host:
            address: redpanda-{{ $i }}.{{ $.Values.namespace }}.svc.cluster.local
            port: 33145
      {{- end }}
      {{- end }}
      rpc_server:
        address: 0.0.0.0
        port: 33145
        advertised_address: ${POD_NAME}.{{ .Values.namespace }}.svc.cluster.local
        advertised_port: 33145
      kafka_api:
        - address: 0.0.0.0
          port: 9092
          advertised_address: ${POD_NAME}.{{ .Values.namespace }}.svc.cluster.local
          advertised_port: 9092
      admin:
        - address: 0.0.0.0
          port: 9644
      pandaproxy:
        - address: 0.0.0.0
          port: 8082
          advertised_address: ${POD_NAME}.{{ .Values.namespace }}.svc.cluster.local
          advertised_port: 8082
      schema_registry:
        - address: 0.0.0.0
          port: 8081
          advertised_address: ${POD_NAME}.{{ .Values.namespace }}.svc.cluster.local
          advertised_port: 8081
  generate-config.sh: |
    #!/bin/sh
    sed "s/\${POD_NAME}/${POD_NAME}/g" /etc/redpanda/redpanda.yaml.template > /etc/redpanda/redpanda.yaml
    cat /etc/redpanda/redpanda.yaml

