apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: istio-system
  template:
    metadata:
      name: istio
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: multipass
      source:
        repoURL: https://github.com/coolsaigit/multipass.git
        targetRevision: main
        path: gitops/helm/istio
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

