apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: monitoring
            valuesFile: ../../kustomize/overlays/dev/prometheus/values-dev.yaml
  template:
    metadata:
      name: prometheus-{{environment}}
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: multipass
      source:
        repoURL: https://github.com/coolsaigit/multipass.git
        targetRevision: main
        path: gitops/helm/prometheus
        helm:
          valueFiles:
            - values.yaml
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipCRDs=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

