namespace: minio

replicas: 1

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  apiPort: 9000
  consolePort: 9001

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

credentials:
  rootUser: minioadmin
  rootPassword: minioadmin

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

